version: "3"
name: "nginx-service"

services:
  nginx:
    container_name: nginx
    image: nginx:1.22.1-alpine
    ports:
      - "443:443"
      - "80:80"
    restart: always
    volumes:
      - /var/www/html:/var/www/html
      - ./config/nginx/cert:/etc/nginx/cert
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]
      timeout: 10s