name: Deploy Hugo site to server

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
    deploy:
        runs-on: debian-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
        - name: Pull Repo
          uses: actions/checkout@v3
          with:
            submodules: true  # Fetch Hugo themes (true OR recursive)
            fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: '0.143.1'
            extended: true

        - name: Build
          run: hugo --minify

        - name: Deploy
          uses: burnett01/rsync-deployments@5.2
          with:
            switches: -avzr --delete
            path: ./public
            remote_path: /var/www/html/
            remote_host: ${{ secrets.DEPLOY_HOST }}
            remote_port: ${{ secrets.DEPLOY_PORT }}
            remote_user: ${{ secrets.DEPLOY_USER }}
            remote_key: ${{ secrets.DEPLOY_KEY }}